# Generated by Django 5.0.1 on 2024-01-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='about',
            field=models.CharField(db_index=True, max_length=10000),
        ),
    ]
