# Generated by Django 5.0.1 on 2024-01-28 05:29

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_employee_about'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=django.contrib.postgres.indexes.HashIndex(fields=['about'], name='hr_employee_about_ix'),
        ),
    ]
